version: "3.9"
services:
  load_balancer:
    build: ./load_balancer
    image: load_balancer
    container_name: load_balancer
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    networks:
      - net1
    environment:
      - FLASK_ENV=development

  server_1:
    build: ./server
    image: server
    container_name: server_1
    networks:
      - net1
    environment:
      - SERVER_ID=1

  server_2:
    build: ./server
    image: server
    container_name: server_2
    networks:
      - net1
    environment:
      - SERVER_ID=2

  server_3:
    build: ./server
    image: server
    container_name: server_3
    networks:
      - net1
    environment:
      - SERVER_ID=3

networks:
  net1:
    driver: bridge
